### ISSUE TITLE
python module validation of observation_id field - too stringent?

### ISSUE THREAD

**Issue by alaity47** [opencadc/CAOM#12]
Several of our collections at IRSA have observationid values that include spaces or slashes, and we're running into the following error trying to export them with the python caom2 library:

`invalid observation_id: may not contain space ( ), slash (/), escape (\), or percent (%)`

I reached out to @pdowler, who said this is to ensure that observation_id does not contain any characters aren't URI-safe, and suggested I open an issue here for discussion. 

We don't use that field for URI population and haven't been able to find any documentation indicating that the observation_id string has any restrictions.   

Is the caom2 module possibly being too stringent in how it validates this column?     

(FYI we use CAOM 2.3, and the python module caom2 2.3.8.4)

**Comment by pdowler** [comment]
closing in favour of #3
